(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



$PyMLibDirectory::usage="The default dir for finding python scripts";
$PyRunHeader::usage="The header to insert before PyRun calls";


PyMScript::usage="Represents a mathematica_script inside a python run";


Begin["`Private`"];


ToPython (* Load all of the symbolic parameters *)


$PyMLibDirectory=
	PackageFilePath["Resources"];


$PyRunHeader:=
	PyColumn[{
		PyIf[PyNot@PyMemberQ[$PySysPath,PyString@$PyMLibDirectory]][
			PySysPathInsert[PyString@$PyMLibDirectory],
			PyImport["MLib"],
			PyAssign[
				PyIndex[
					PyDot["MLib","mathematica_export_parameters"],
					PyString@"Delimiter"
					],
				PyString@$PyExportKey
				]
			]
		}]


End[];



